# ansible-playbook q8-ans.yml
- name: webcontent playbook
  hosts: webservers
  tasks:
    - name: Ensure group webdev exists
      group:
        name: webdev
        state: present
    - name: create a /webdev direectory
      file:
        path: /webdev
        state: directory
        group: webdev
        mode: 2775
        setype: httpd_sys_content_t

    - name: create symbolic link
      file:
        src: /webdev
        dest: /var/www/html/webdev
        state: link
        force: yes
    
    - name: copy using inline content
      copy:
        content: "Development"
        dest: /webdev/index.html
        setype: httpd_sys_content_t
    
    - name: allow http traffic
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled