# ansible-playbook q8-ans.yml
- name: Create web directory
  hosts: dev
  roles:
  - apache
  tasks:
  - name: Give insecure permissions to an existing file
    ansible.builtin.file:
      path: /webdev
      state: directory
      group: wheel
      mode: '2775'

  - name: Create a symbolic link
    ansible.builtin.file:
      src: /webdev
      dest: /var/www/html/webdev
      state: link

  - name: Copy file content
    ansible.builtin.copy:
      dest: /webdev/index.html
      content: 'Development'
      setype: httpd_sys_content_t
